### PR TITLE
wskdeploy can now run as an openwhisk action.

### PR DESCRIPTION
**Pull request by lionelvillard**
This PR enables wskdeploy to run as an OpenWhisk action inside a go docker container. (#189)

- New flags have been added:

      --apihost HOST         whisk API HOST
      --apiversion VERSION   whisk API VERSION
      -u, --auth KEY             authorization KEY

- Modified flags:
      -m now accept URL pointing to the manifest.

- Read action content either from local file system or remote http location.
- Fix duplicated persistent flag declarations.

### CODE REVIEW

**Comment by mrutkows** [comment]
@lionelvillard very cool.  Do you have a practical example that you would care to promote?

**Comment by mrutkows** [comment]
Would suggest changing/adding -m to --manifest (short single letter switches are usually reserved for toggle functions, filenames usually are part of the syntax or spelled out for files).

**Comment by mrutkows** [comment]
Also, we would need to support an optional --deployment <file>

**Comment by lionelvillard** [comment]
-m and -d are existing flags. I suggest to open separate issue to consider changing the wskdeploy syntax.

As for the practical example, what about the simple helloworld usecase? @mrutkows Do you have something else in mind

**Comment by mrutkows** [comment]
@lionelvillard just because something is cool doesn't mean we should do it unless we have a customer (or end user) use case to show a practical example.

**Comment by lionelvillard** [comment]
You are right, we haven't described the practical use cases somewhere. I'm currently working on the `deploy application on Bluemix` feature accessible from the OpenWhisk Hub. There are also several practical use cases, like automatic deployment after github release, server-side deployment of large assets, travis integration, etc..

**Comment by jthomas** [comment]
I haven't been involved with this project so I'm sure I should be doing the review 😎

This does sound like a good idea to me, will help to build serverless deployment pipelines.

**Comment by paulcastro** [comment]
@lionelvillard LGTM, one small comment.  Should we be more consistent with using `log` vs `fmt`?  When we're in interactive mode, mixing logs and fmts sometimes causes bad printing in the  terminal, e.g. error messages get printed over prompts, etc.  What do you think?

**Comment by lionelvillard** [comment]
@paulcastro It seems that in Go neither os.Stdout nor os.Stderr is buffered. So mixings stderr/stdout should not be an issue.

**Comment by paulcastro** [comment]
Ok great - I had trouble before and had to switch some statements from log to fmt to get things to be pretty.  I haven't tried what happens if I dump fmt completely.  Just want things to look nice for the user :-)

**Pull request merged**
