### PR TITLE
Add GitHub based dependencies key to deploy and undeploy

### PR DESCRIPTION
**Pull request by houshengbo**
This is a first cut at adding dependencies to a manifest.yml file.  This adds a `dependencies` key where the dependency is a GitHub repo.

```
package:
  name: opentest
  dependencies:
      hellowhisk:
          url: https://github.com/paulcastro/hellowhisk
          version: 1.0.1
      myCloudant:
           source: /whisk.system/cloudant
           inputs:
                  dbname: MyGreatDB
  sequences:
    mySequence:
      actions: hellowhisk/greeting, hellowhisk/httpGet
  triggers:
    myTrigger:
  rules:
    myRule:
      trigger: myTrigger
```
This manifest references a GitHub project aliased as "hellowhisk", version 1.0.1 at the given URL.  If `version` is not specified, it will pull from `master`.

Dependencies that specify a `source` are interpreted as bindings, and we do a package bind.  `url` specifies a GitHub dependency and is treated as an independent deployment.  For example, the root package `opentest` refers to entities in the `hellowhisk` package using the package name format.  The following happens on deploy

1. wskdeploy downloads and unpacks a zip file of the gihub repo in `$ProjectPath/Packages/<dependencyname>`
2. Deploys dependencies first
3. Deploys root package

This PR does not include dependency graph management so use at your own risk.

There is a use case in tests/usescases/deptest that illustrates a project that has no local source code, just a manifest that combines the entities in a dependency.

### CODE REVIEW

**Comment by houshengbo** [comment]
@paulcastro Paul This PR should pass.
The only critical change is to change if params.ManifestPath != "" { to if params.ManifestPath == "" {

**Comment by lzbj** [comment]
@houshengbo , can you update this PR, there are two commits inside. Also could you please add some CI code for this PR? It would help people under what this PR trying to do, if it resolves the dependency or Package binding issue, I think we're very close to wskdeploy version 1.0, right? Any comments? @mrutkows @paulcastro

**Comment by houshengbo** [comment]
@lzbj I think @paulcastro will take care of this PR, which is a derivative from one of his PRs. 
I have already made sure this PR is able to pass all the CI tests.

I am not sure what you mean by CI code. Do you mean adding more tests for the code change?

**Comment by lzbj** [comment]
@houshengbo , ok, got it, thank you. I think this patch is very important, so the corresponding use case and test code could help people know how to use it.

**Comment by paulcastro** [comment]
@lzbj if you approve, could you merge this?  I con't think I should merge my own code.  I can add comment, etc. in a separate PR.

**Comment by mrutkows** [comment]
@paulcastro Did we ever talk about supporting this in the spec.?

**Comment by paulcastro** [comment]
@mrutkows  Issue #41?

**Comment by paulcastro** [comment]
I'll close this and open a new PR -- I'm making changes to the manifest.

**Pull request closed without merging**
