### PR TITLE
Add support for in-line parameters

### PR DESCRIPTION
**Pull request by paulcastro**
Fixes issue #146.

Adds a `parameters` key to the manifest file which allows setting of parameters:

```
actions:
    myAction:
         parameters:
                 name: Paul
                 vehicle: airplane
```

The presence of a deployment.yaml file will overwrite any parameters set in the manifest file.

### CODE REVIEW

**Comment by lzbj** [comment]
@paulcastro , there are some conflicts with the master branch after merged your former PR, could you please check it and resubmit?

**Comment by paulcastro** [comment]
@lzbj Resolved

**Comment by lzbj** [comment]
@paulcastro , sorry, still show conflicts when I try to merge it, perhaps you need to rebase the master, resolve the conflicts, then resubmit.

**Comment by paulcastro** [comment]
@lzbj its fine.

**Comment by mrutkows** [comment]
@paulcastro I would prefer not adding "parameters" as a key as it is redundant to inputs; it will break our intended alignment with OpenAPI, as well as long term plans to be part of efforts such as Lambda has in Cloud Formation.

**Comment by paulcastro** [comment]
@mrutkows `Inputs` is still an allowed key in this PR.  Is your change request that we allow value setting in the inputs section? In other words:

```
actions:
    myAction:
        inputs:
                 name: Paul
                 vehicle: airplane
```

Per my comments on #146, it seems cleaner to have a different section to set parameter values than to overload the schema definition using `inputs` and `outputs`.

In the current PR, this is allowed:

```
actions:
    myAction:
         inputs:
                 name:
                       type: string
                 airplane:
                       type: string
         parameters:
                 name: Paul
                 vehicle: airplane
````

**Comment by paulcastro** [comment]
Updated to overload `inputs` as the key to set parameter bindings in the manifest file.  Note that this overloads the schema definition section and will need to be modified if we need to infer schema information from this section in the future.

**Comment by lzbj** [comment]
@paulcastro , yes, merged, I used the github UI to do the merge, then it's succeeded.
If I use the git cli, I always got conflicts errors, Just FYI, I referenced a wiki here:
https://github.com/openwhisk/openwhisk/wiki/Contributing:-Git-guidelines

**Pull request merged**
